version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_task_001
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scan_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "33061:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro 